export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_OTP = 'SET_OTP';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';